# @package _global_
defaults:
  - _self_
  - data: ct_abca
  - model: classifier
  - callbacks: default
  - logger:
  - trainer: gpu
  - paths: default
  - hydra: default
  - experiment:

task_name: train
train: true
test: true
ckpt_path:
seed: 2025
